# -*- coding: utf-8 -*-
"""Spam filter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f9GKM7_GyLXk9Tw5scGs_zaA-QRZwevz
"""

import pandas as pd

df = pd.read_table("https://raw.githubusercontent.com/arib168/data/main/spam.tsv")
df

df.info()

x = df['message'].values

y = df['label'].values

df['message'][5567]

df['label'].value_counts()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0)

x_train.shape

x_test.shape

from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(stop_words='english')
x_train_vect = vect.fit_transform(x_train)
x_test_vect = vect.transform(x_test)

from sklearn.svm import SVC
model1 = SVC()

model1.fit(x_train_vect,y_train)

y_pred1 = model1.predict(x_test_vect)
y_pred1

y_test

from sklearn.metrics import accuracy_score
accuracy_score(y_pred1,y_test)

from sklearn.pipeline import make_pipeline
model2 = make_pipeline(CountVectorizer(),SVC())
model2.fit(x_train,y_train)

y_pred2 = model2.predict(x_test)
y_pred2

y_test

from sklearn.metrics import accuracy_score
accuracy_score(y_pred2,y_test)

from sklearn.naive_bayes import MultinomialNB
model3 = MultinomialNB()

model3.fit(x_train_vect,y_train)

y_pred3 = model3.predict(x_test_vect)
y_pred3

y_test

from sklearn.metrics import accuracy_score
accuracy_score(y_pred3,y_test)

from sklearn.pipeline import make_pipeline
model4 = make_pipeline(CountVectorizer(),MultinomialNB())
model4.fit(x_train,y_train)
y_pred4 = model4.predict(x_test)
y_pred4

y_test

from sklearn.metrics import accuracy_score
accuracy_score(y_pred4,y_test)

import joblib
joblib.dump(model4,'spam-ham')

import joblib
text_model = joblib.load('spam-ham')

text_model.predict(["free tickets sold"])

pip install streamlit --quiet

import streamlit as st

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import joblib
# 
# st.title("SPAM HAM CLASSIFIER")
# text_model = joblib.load('/content/spam-ham')
# ip = st.text_input("Enter the message :")
# op = text_model.predict([ip])
# if st.button('PREDICT'):
#   st.title(op[0])

!streamlit run app.py &npx localtunnel --port 8501

